### PR TITLE
Add tests for mean and ev

### PR DESCRIPTION
**Pull request by fdietze**

### CODE REVIEW

**Comment by fdietze** [comment]
Not sure how this can work for JS now...

**Comment by fdietze** [comment]
Forgot to run the tests.

**Comment by fdietze** [comment]
There were go now the tests can be fixed

**Comment by fdietze** [comment]
@jliszka ok it works! Ready to squash and merge. 👍

**Review by jliszka — APPROVED** [review]
thank you!!

**Pull request merged**
